### PR TITLE
Added helper method to generate webtask urls and provide Promise for calling them

### PR DESCRIPTION
**Pull request by bananaoomarang**
Not sure about the API, currently also only supports named tokens, but I can't see why you would want to use a token unless generating a task on the fly, in which case you're better off on your own anyway.

### CODE REVIEW

**Comment by tjanczuk** [comment]
Is this module only meant to be used from within the sandbox, or do we have an aspiration to create a general purpose webtask client for Node.js? If the latter, we should focus more on the regular async programming model since this is still the bread & butter of Node.js programming.

**Comment by ggoodman** [comment]
@tjanczuk I have created the beginnings of a general-purpose webtask client for Node.js in here: https://github.com/auth0/wt-cli/blob/master/index.js

This code supports both Promises and typical node-style callback functions.

**Comment by tjanczuk** [comment]
So what is the plan wrt this repo vs the "library" code in wt-cli? Should we create something new like `webtask` (still free on NPM) specifically for client lib bits? I can see how both the getWebtask as well as the "add-on" programming models (express, connect) could live there. But first and foremost the library should have some usable functions to call HTTP API.

**Comment by darkyen** [comment]
@tjanczuk  if its still free please do the WT-Client part :+1:

**Comment by ggoodman** [comment]
@darkyen please check out auth0/sandboxjs. Hope that is what you are looking for!

**Comment by darkyen** [comment]
@ggoodman Thanks! 
Although I needed a client separately, I am making a badge (like heroku) that you click and it deploys the repo to a webtask (after transpiling, adding js only libs etc etc),  using a webtask (also takes care of github's git hooks).

**Comment by ggoodman** [comment]
Closing for now.

**Pull request closed without merging**
