### PR TITLE
Validate accept an audience secret parameter on webtask creation, and…

### PR DESCRIPTION
**Pull request by fsargent**
… use it to validate tokens.

### CODE REVIEW

**Comment by fsargent** [comment]
This more appropriately addresses #27

**Comment by ggoodman** [comment]
Hey @fsargent, thanks for your initiative. We have this on our radar but can't commit to any specific timeline right now.

To facilitate reviewing, could you share a bit more context about why these changes are needed and how the PR addresses this?

**Comment by fsargent** [comment]
hi @ggoodman, Tokens issued by Auth0 don't have the audience parameter as equalling the client ID. Instead, the audience parameter is specified by the Auth0 tenant depending on what API you wish to give permissions to.  This change allows for people to specify what they'll allow or accept for the audience parameter.

**Comment by fsargent** [comment]
https://auth0.com/docs/tokens/access-token#access-token-format

**Comment by fsargent** [comment]
Hi @ggoodman,

First off, thanks for the detailed response. 

You're absolutely right, I'm _hoping simply to authenticate incoming requests that have an Access Token in the Authorization header._

I'll look into the other JWT package.

From my reading of the Auth0 documentation and OAuth2 spec the id_token was not used at all for authentication, but instead was a payload containing the user's information, link to their gravatar, etc. 
https://auth0.com/docs/api-auth/why-use-access-tokens-to-secure-apis
In the scenario where I'd use the auth0 package to validate a JWT sent from a client to a webtask, the webtask would be considered a secure API, not a client.
Then again, I guess I can do that with the other library.

Thanks!

**Pull request closed without merging**
